### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by TCROC** [LyonSyonII/dioxus-tailwindcss#1]
This is awesome!  We would love to use it as a template for our projects!  Could you add a LICENSE file to it so that we can?  Thanks!

**Comment by LyonSyonII** [comment]
Of course, thank you!

**Comment by LyonSyonII** [comment]
Done

**Comment by TCROC** [comment]
Awesome! Thanks again! I was playing around a few days ago got tailwind cli hot reloading with dioxus. Then I saw your repo yesterday. Your solution is much more elegant imo, but I'll publish mine as well when I get around to it in case there is anything that might be of use :)
